[package]
name = "the-complete-shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
errno = "0.3.9"
is-terminal = "0.4.13"
rand = "0.8.5"
rustyline = "14.0.0"
